#!/usr/bin/python3
"""Compiles a Python script file into $PYFILEc"""
import os
import py_compile

pyfile = os.environ.get("PYFILE")
print("Compiling {} ...".format(pyfile))
py_compile.compile(pyfile, cfile=pyfile + "c")
